# Generated by Django 2.0 on 2020-06-30 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0030_auto_20200628_0736'),
        ('core', '0006_auto_20190305_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('kewword', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('og_title', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('og_image', models.ImageField(blank=True, default=None, max_length=255, null=True, upload_to='seo', verbose_name='Og Image')),
                ('og_description', models.TextField(blank=True, default=None, null=True)),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='catalogue.Product')),
            ],
        ),
    ]
