# Generated by Django 2.0 on 2020-07-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0007_conditionaloffer_exclusive'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditionaloffer',
            name='banner',
            field=models.ImageField(blank=True, default=None, max_length=255, null=True, upload_to='images', verbose_name='Banner Image'),
        ),
    ]
