# Generated by Django 2.0.13 on 2020-06-14 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0020_product_new_arrival'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shot_description',
            field=models.CharField(blank=True, default=True, max_length=120, null=True),
        ),
    ]
