# Generated by Django 2.0.13 on 2020-06-14 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0021_product_shot_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shot_description',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
