# Generated by Django 2.0.13 on 2020-06-18 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0026_auto_20200614_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shot_description',
            field=models.TextField(blank=True, max_length=420, null=True),
        ),
    ]
