# Generated by Django 2.0.13 on 2020-06-18 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0027_auto_20200618_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shot_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
