# Generated by Django 2.0.13 on 2020-06-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0028_auto_20200618_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='warranty',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
