# Generated by Django 2.0.13 on 2020-06-28 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0029_auto_20200628_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='warranty',
            field=models.CharField(blank=True, default='Warranty not available', max_length=220, null=True),
        ),
    ]
