# Generated by Django 2.0.13 on 2020-07-02 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0030_auto_20200628_0736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='shot_description',
            new_name='short_description',
        ),
    ]
