# Generated by Django 2.0.13 on 2020-07-08 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0031_auto_20200702_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_service',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_description',
            field=models.CharField(blank=True, default='', max_length=180, null=True),
        ),
    ]
